### ISSUE TITLE
LUCAS to shapefile

### ISSUE THREAD

**Issue by izzyrich** [izzyrich/dissertation#4]
Hi everyone,

Hope you are both well! I've been working on converting the LUCAS dataset to a shapefile (see my script [here](https://github.com/izzyrich/dissertation/blob/master/code/lucas_to_shapefile.R)).

I thought I converted it successfully into a shapefile. However, when I tried to import it into GEE using table upload, it says it is not a valid shapefile. It would be great if either of you could take a look at my script and see where I've gone wrong. I'll keep trying too!

Thanks,
Izzy

**Comment by IslaMS** [comment]
Hi @izzyrich ,

One thing that I have discovered with loading up shape files is that the Earth Engine does not like .sbx files. But, if you just do not load those files, but load up all the other associated shape files, then it seems to work fine.  Could this be your problem?

Isla

**Comment by gndaskalova** [comment]
Hi @izzyrich 

One other thing to look into is the differences between the U400 and U112 classes and to think about what you will consider as "abandoned land" - e.g. where does fallow land go?

If you save your shapefile and then import it again in R and plot it, does it look right?

This tutorial seems to be doing what you need to do https://datacarpentry.org/r-raster-vector-geospatial/10-vector-csv-to-shapefile-in-r/

Perhaps your issue was that you didn't set the extent of the shapefile.

Gergana

**Comment by izzyrich** [comment]
Hi @IslaMS and @gndaskalova,

Thanks for both of your very speedy replies and sorry for my extremely delayed one! I've edited my code and now it seems to be working! All loaded into GEE as well. 

I've considered your comment, Gergana, about what to consider abandoned land. It seems like there are differences between 2009 data and 2012-more recent data. I believe I will be using 2012, 2015 and 2018 data with the U410 land use classification (abandoned) with the following land covers: croplands (B), shrublands (D) and grasslands (E). U112, D10 and D20 are also cited to be abandoned agricultural land so I have also included these. This is something I will speak to you about in our meeting tomorrow. 

Thanks for all your help,
Izzy
